name: vimigo_attendance_list
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  timeago: ^3.0.2
  sqflite: ^2.2.8+4
  http: ^1.0.0
  intl: ^0.18.1
  chewie: ^1.0.0
  video_player: ^2.2.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Video/tutorial.mp4

  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
